server.ssl.enabled=true
server.ssl.key-store=keystore/mylibs.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${KEYSTORE_PASSWORD:changeit}
server.ssl.key-alias=${KEYSTORE_ALIAS:mylibs}
server.ssl.key-password=${KEYSTORE_PASSWORD:changeit}

